---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cupcake-debian
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  extra_vars:
    install_whisper: false
    python_version: "3.11"
    pg_version: "15"
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
